# Самостоятельная работа 2. Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [27]:
import numpy as np
np.__version__

'1.26.0'

2) Создать нулевой вектор размера 10

In [28]:
zero_vector = np.zeros(10)
zero_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3) Создать вектор заполненный 7-ами размера 7

In [32]:
seven_seven_vector = np.full(7, 7)
seven_seven_vector

array([7, 7, 7, 7, 7, 7, 7])

4) Создать вектор заполненный четными числами от 10 до 100

In [30]:
even_vector = np.arange(10, 101, 2)
even_vector

array([ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98, 100])

5) Создать массив случайных чисел и развернуть его задом наперёд

In [58]:
rand_array = np.random.randn(10)
rand_array

array([-0.79868855,  0.39557108, -0.45478349, -0.61751636,  0.82239132,
        0.59042458, -0.25890615, -0.21703108,  0.39669106, -0.0793457 ])

In [59]:
rand_array[::-1]

array([-0.0793457 ,  0.39669106, -0.21703108, -0.25890615,  0.59042458,
        0.82239132, -0.61751636, -0.45478349,  0.39557108, -0.79868855])

6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [41]:
digits_matrix = np.arange(0, 9).reshape((3,3))
digits_matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [44]:
diag_matrix = np.eye(4, k = 1)
diag_matrix

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [47]:
seven_diag_matrix = np.full((4, 4), 7)
for i in range(4):
    seven_diag_matrix[i, i] = i + 1
seven_diag_matrix   

array([[1, 7, 7, 7],
       [7, 2, 7, 7],
       [7, 7, 3, 7],
       [7, 7, 7, 4]])

9) Создать матрицу размера 5 на 5 заполненную числами от 0 до 4 в строках.

In [50]:
five_five_matrix = np.zeros((5, 5))
for i in range(5):
    five_five_matrix[i] = np.arange(5)
five_five_matrix

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [77]:
rand_matrix = np.random.random_sample((10, 10))
means = np.mean(rand_matrix, axis = 1)
rand_matrix -= means.reshape(-1, 1)
rand_matrix

array([[-0.01295057,  0.24836739,  0.3884347 , -0.38987397,  0.32035311,
        -0.45393362, -0.1679352 ,  0.32057482, -0.25367965,  0.00064298],
       [ 0.53284942, -0.22599436, -0.18874003,  0.17217392,  0.34730543,
        -0.00538211, -0.35193836,  0.27297839, -0.24426368, -0.30898861],
       [ 0.20075341, -0.00925789,  0.02251002, -0.12640565,  0.12230108,
        -0.5035086 ,  0.18670037, -0.08723871,  0.21891818, -0.0247722 ],
       [-0.37980343, -0.17263893,  0.32973989,  0.03894345, -0.50118591,
         0.31019847, -0.18032587,  0.03040778,  0.24166995,  0.28299461],
       [-0.18281864,  0.35778967, -0.23828526,  0.20354701,  0.01842155,
        -0.16843903,  0.19671088, -0.29641414, -0.39862278,  0.50811073],
       [ 0.25671832, -0.04256815,  0.10980935,  0.02225307, -0.27269563,
         0.32118088, -0.39955457, -0.39493215,  0.14875675,  0.25103213],
       [-0.32419861,  0.26719373, -0.25949472,  0.065836  ,  0.2986678 ,
         0.12222293,  0.13077615, -0.47627086

11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [66]:
rand_matrix_2 = np.random.random_sample((10, 10))
medians = np.median(rand_matrix_2, axis = 0)
rand_matrix_2 -= medians
rand_matrix_2

array([[ 0.21652592, -0.50151859,  0.00555481,  0.04104353,  0.2815258 ,
         0.36283162,  0.33555343, -0.6076663 ,  0.30917492, -0.37346172],
       [-0.06954225, -0.16842575,  0.12162019, -0.4211657 , -0.22206505,
         0.46700549, -0.25885326,  0.0623989 ,  0.10278237, -0.27045558],
       [ 0.43051812,  0.16842575,  0.34644009, -0.18007146,  0.34333143,
        -0.25804411, -0.01628672,  0.15824134, -0.33965623,  0.54894636],
       [ 0.24366589, -0.55637639,  0.21513485, -0.03680523,  0.06544694,
        -0.24021197,  0.01628672,  0.1520935 , -0.04357597,  0.36378296],
       [-0.36159245,  0.21671159, -0.00555481, -0.43612725, -0.17068629,
         0.18080005,  0.32777456,  0.19403716, -0.25748062, -0.10214019],
       [-0.0052706 ,  0.36778955, -0.27937872,  0.3006746 , -0.06544694,
         0.30250571, -0.29880071, -0.24403984,  0.4200568 ,  0.31149387],
       [-0.04502193,  0.18620807,  0.41046595, -0.17294156, -0.21933607,
         0.46407001, -0.05376183,  0.27932168

12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [79]:
rand_matrix_3 = np.random.random_sample((5, 5))
max_matrix = np.max(rand_matrix_3, axis = 1).reshape(5, 1)
min_matrix = np.min(rand_matrix_3, axis = 1).reshape(5, 1)
result = np.hstack((rand_matrix_3, max_matrix, min_matrix))
result.shape


(5, 7)

13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [105]:
numbers = np.arange(1, 51)
even_numbers = numbers[numbers % 2 == 0].reshape(5, 5)
odd_numbers = numbers[numbers % 2 != 0].reshape(5, 5)
mult_matrix = even_numbers.dot(odd_numbers)
print(mult_matrix)
# опеделитель данной матрицы равен 0, поэтому обратной матрицы не существует
# mult_matrix_inv = np.linalg.inv(mult_matrix)
print(np.linalg.det(mult_matrix))
#print(mult_matrix_inv)

[[ 830  890  950 1010 1070]
 [1880 2040 2200 2360 2520]
 [2930 3190 3450 3710 3970]
 [3980 4340 4700 5060 5420]
 [5030 5490 5950 6410 6870]]
0.0


14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами. 

In [147]:
chess_field = np.zeros((8, 8), dtype = int)
chess_field[::2, 0::2] = 1
chess_field[1::2, 1::2] = 1
chess_field

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])