# Линейная алгебра с Numpy

С помощью [Sympy](http://www.sympy.org/en/index.html) можно выполнять символьную линейную алгебру, но для числовых вычислений [Numpy](http://www.numpy.org/) является высокопроизводительная библиотека, которую следует использовать при решении математических и инженерныхзадач.

Описание:

> NumPy — это фундаментальный пакет для научных вычислений на Python. Он содержит, среди прочего: [...]
 линейную алгебру, преобразование Фурье и теорию вероятностей.

В этом разделе научимся, как:

- работать с матрицами;
- решать матричные уравнения;
- рассчитывать обратную матрицу и определители.

## Работа с матрицами

Создать матрицу с помощью Numpy несложно. В качестве примера рассмотрим следующее:

$$
A = \begin{pmatrix}
5 & 6 & 2\\
4 & 7 & 19\\
0 & 3 & 12
\end{pmatrix}
$$

$$
B = \begin{pmatrix}
14 & -2 & 12\\
4 & 4 & 5\\
5 & 5 & 1
\end{pmatrix}
$$


Сначала, как и в Sympy, нам нужно импортировать Numpy:

In [1]:
import numpy as np

Теперь можем определить $A$:

In [2]:
A = np.matrix([[5, 6, 2],
               [4, 7, 19],
               [0, 3, 12]])

In [ ]:
A

In [4]:
B = np.matrix([[14, -2, 12],
               [4, 4, 5],
               [5, 5, 1]])

In [ ]:
B

Можно получить как следствие:

- $5A$ (или любое другое скалярное число, кратное $A$);
- $A ^ 3$ (или любой другой показатель $A$);
- $A + B$;
- $A - B$;
- $AB$

In [ ]:
5 * A

In [ ]:
A ** 3

In [ ]:
A + B

In [ ]:
A - B

In [ ]:
A * B

---

**УПРАЖНЕНИЕ 1** Решить $A ^ 2 – 2 A + 3$ с помощью:

$$A =
\begin{pmatrix}
1 & -1\\
2 & 1
\end{pmatrix}
$$

---

In [2]:
# Решение
A = np.matrix([[1, -1],
               [2, 1]])
A * A - 2 * A + 3

matrix([[0, 3],
        [3, 0]])



## Решение матричных уравнений

Можно использовать Numpy для (эффективного) решения больших систем уравнений вида:

$$Ax=b$$

Проиллюстрируем это:

$$
A = \begin{pmatrix}
5 & 6 & 2\\
4 & 7 & 19\\
0 & 3 & 12
\end{pmatrix}
$$

$$
b = \begin{pmatrix}
-1\\
2\\
1
\end{pmatrix}
$$

In [11]:
A = np.matrix([[5, 6, 2],
               [4, 7, 19],
               [0, 3, 12]])
b = np.matrix([[-1], [2], [1]])

Мы используем команду `linalg.solve`:

In [ ]:
x = np.linalg.solve(A, b)
x

Проверим результат:

In [ ]:
A * x

---
**УПРАЖНЕНИЕ 2** Найти решение матричного уравнения $Bx=b$ (используя $B$).

---

In [3]:
# Решение:
A = np.matrix([[5, 6, 2],
               [4, 7, 19],
               [0, 3, 12]])
b = np.matrix([[-1], [2], [1]])

np.linalg.solve(A, b)

matrix([[ 0.45736434],
        [-0.62790698],
        [ 0.24031008]])



## Обратные матрицы и определители

Найдем обратную матрицу:

In [ ]:
Ainv = np.linalg.inv(A)
Ainv

Проверка $A^{-1}A=\mathbb{1}$:

In [ ]:
A * Ainv

Казалось бы, что матрица не единичная, однако по главной  `1` , а на всех остальных позициях **очень** маленькие числа (однако для компьютера это `0`).

Вычислим детерминант:

In [ ]:
np.linalg.det(A)

---

**УПРАЖНЕНИЕ 2** Вычислите обратную матрицу и определитель $B$ (ранее уже находили).

---

In [7]:
# Решение
Ainv = np.linalg.inv(A)
print(Ainv, np.linalg.det(A), sep = '\n')

[[-0.20930233  0.51162791 -0.7751938 ]
 [ 0.37209302 -0.46511628  0.6744186 ]
 [-0.09302326  0.11627907 -0.08527132]]
-129.00000000000009
