In [7]:
import numpy as np
from scipy.linalg import *

In [2]:
a = 28 # α 
b = 7 # β
g = 3 # γ
t = 1 # θ
m = 1 # μ
v = 3 # ν

In [3]:
# 1
# Решение:
A = np.matrix([[2, 3 + a, 4 - m],
               [b, g, v],
               [5, 10 * m, -2]])
B = np.matrix([[b, -3, 4 + m],
               [a, 4, v],
               [5 * m, 10, -2]])
C = np.matrix([[-1, 3 + m, 4 - v],
               [2, 1, v],
               [5, 5 - m, -2]])

A * B * C

matrix([[-116, 4124, 1147],
        [  84,  765,  135],
        [   0, 1461,  202]])

In [6]:
# 2
# Решение:
G = np.matrix([[2, 3 + a, 4 + m, 6],
               [b + 1, g, v, 12],
               [5, -2, 16, m + 1], 
               [2, 7, 11, -6]])
print(np.linalg.eig(G), np.linalg.det(G), np.linalg.inv(G) , sep = '\n' ) 

EigResult(eigenvalues=array([ 25.5269861 , -16.71501716,  -4.8064692 ,  10.99450026]), eigenvectors=matrix([[-0.76006434, -0.76548408,  0.85583491,  0.74714212],
        [-0.4652843 ,  0.50464083, -0.06726738,  0.33328435],
        [-0.35935452,  0.1699277 , -0.16547024, -0.55865635],
        [-0.27690622, -0.36124276, -0.48542899, -0.13639384]]))
22548.0
[[-0.08674827  0.19744545 -0.18041511  0.24800426]
 [ 0.025102    0.00319319 -0.02448111  0.02332801]
 [ 0.02456981 -0.05694518  0.10324641 -0.05490509]
 [ 0.04541423 -0.03485897  0.10058542 -0.1574419 ]]


In [9]:
# 3
# Решение:
A = np.matrix([[2, -5, 7],
               [8, 1, 9],
               [3, -4, 12]])
C = np.matrix([[-25, -17, 78],
               [11, 89, 76],
               [-5, 24, 115]])

print(f'B = {np.linalg.solve(A, C)}')

B = [[-3.  4.  1.]
 [ 8. 12. -4.]
 [ 3.  5.  8.]]


In [11]:
# 4 
# Решение
A = np.matrix([[3, 1, 1, g],
               [1, -m, v, 4],
               [-5, 0, -1, -7], 
               [1, -6, a, 6]])
f = np.array([a, b, -5, 3]).reshape(4, 1)

x = solve(A, f)
x

array([[-12.60474308],
       [ 33.34782609],
       [  5.79841897],
       [  8.88932806]])